### ISSUE TITLE
Cannot run rub on upgraded project

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/rub-cli#11]
A colleague upgrades a project from legacy Rub to new Rub on SVN. Updating my local version doesn't remove the `buildkit` folder completely because it contains an unversioned `node_modules` folder.

Attempting to run new Rub leads to
```shellsession
Legacy rub is installed. Please use './rub' to run the legacy version
[Finished in 0.2s]
```

Please can we make the legacy check more robust.

**Comment by oliverfoster** [comment]
Closing as marginal issue.
