### ISSUE TITLE
Warning: Helpers.isPathIncluded is not a function

### ISSUE THREAD

**Issue by simondate** [cgkineo/rub-cli#18]
I get this error message whenever I try to build a course with Rub with fw2.

Makes it so the course doesn't recompile and I can't use grunt either afterwards

**Comment by oliverfoster** [comment]
Gonna need much more info. Working fine here.

**Comment by simondate** [comment]
Steps to replicate:

1. ensure node version is `6.14.3`

**Comment by simondate** [comment]
Steps to replicate:

1. ensure node version is `6.14.3`
2. run `adapt create course` using default settings but change branch to `default`
3. cd in and run `rub -ds`
4. The build fails and no html file is created in build.

**Comment by oliverfoster** [comment]
You should be able to fix using:
1. `npm install -g rub-cli`
2. `rub patch`
3. `rub -d`

**Comment by simondate** [comment]
Working now. Cheers @

**Comment by oliverfoster** [comment]
np 👍
