### ISSUE TITLE
Zip for AAT upload

### ISSUE THREAD

**Issue by simondate** [cgkineo/rub-cli#20]
It would be great if you could create a command to zip up a course for AAT upload. I've been having problems zipping up the wrong things. Would save a lot of headaches if this could be automated to a command. In particular, having to remove `.git` folders is a pain.

**Comment by oliverfoster** [comment]
You want a zip file filter?

**Comment by simondate** [comment]
Just a way to create a .zip to upload to the AT in the same way you can create a .zip of the build. It would copy all the files from here https://github.com/adaptlearning/adapt_authoring/wiki/Importing-Courses#importing-the-course-source-code ignoring any `.git` folders.

**Comment by oliverfoster** [comment]
new command `rub zipaat`

could you test?

**Comment by oliverfoster** [comment]
fixed
