### ISSUE TITLE
Error on rub translate:export

### ISSUE THREAD

**Issue by webcodemonkey** [cgkineo/rub-cli#26]
We're having an issue when running command `rub translate:export`. We get the following errors: 
> m01: Warning: Cannot read property 'hasOwnProperty' of undefined
> m02: Warning: Cannot read property 'hasOwnProperty' of undefined

Here is the results of `rub -V`:
  
>Adapt Framework v3.2.0
>Rub v0.0.38
>Node v6.9.5

How can I resolve this issue so I can get the CSV over to the translators?

**Comment by oliverfoster** [comment]
Morning. Having a look shortly.

**Comment by oliverfoster** [comment]
It looks all fine to me:
![image](https://user-images.githubusercontent.com/7974663/58870041-4b2eb480-86b7-11e9-8a7d-24d2b5421001.png)

I'll need a copy of your source files if I am to debug any further.
I hangout here https://gitter.im/adaptlearning/adapt_framework

**Comment by webcodemonkey** [comment]
I'm going to update framework and node to see if that helps. If not, I will reach out on Gitter. I will close this issue if I get it solved.

**Comment by webcodemonkey** [comment]
@oliverfoster Quick question... if we have components without some schemas defined, could this be the cause?

**Comment by webcodemonkey** [comment]
@oliverfoster I have confirmed it was the lack of schema that was causing the issue. Thanks for the help, I can take it from here.

**Comment by oliverfoster** [comment]
Lovely. 👍  Glad you figured it out.
