### ISSUE TITLE
Rub doesn't report missing blocks

### ISSUE THREAD

**Issue by simondate** [cgkineo/rub-cli#30]
I noticed that whilst building a course that when I forgot to delete a block and Rub gave no error about.

    Adapt Framework  v5.3.0
    Rub              v0.0.43
    Node             v12.13.1

**Comment by oliverfoster** [comment]
Thanks for the heads up.

**Comment by oliverfoster** [comment]
this is an adapt framework issue https://github.com/adaptlearning/adapt_framework/issues/3134
