### ISSUE TITLE
Build issues with Node 12 on Linux

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/rub-cli#34]
- Ubuntu 18.04 (using [nvm](https://github.com/nvm-sh/nvm) to manage Node)
- tested Node v12.18.3 and v12.18.4 with npm 6.14.6
- `rub -dF` runs through tasks with no errors but does not produce output (js/css etc)

**Comment by oliverfoster** [comment]
cannot reproduce
does it work with node lts?

**Comment by oliverfoster** [comment]
node v12 is old, should update to v14 so I can use the new es spec
