### ISSUE TITLE
Localisation/translation import issue with json

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/rub-cli#37]
### Subject of the issue/enhancement/features
Trying to import json file for translation instead of csv, but getting error on import

### Your environment
Framework, v5.3.0
Windows 10

### Steps to reproduce
Export content to json
Duplicated the en folder in a course within builds folder, and renamed it de (this has the json and images folder in it, but in English)

added a de folder to the languagefiles folder (top level of dev folder) and added in the translated export.json

ran 
`rub translate:import –targetLang=de –format=json`
get error saying that “sorry, the imported file is not valid”

### Expected behaviour
Should import the json

### Actual behaviour
Get above error

### Screenshots (if you can)
attached. (i've blanked out part of the file path
![Screenshot 2021-04-13 171128](https://user-images.githubusercontent.com/7137955/114585394-7f903600-9c7b-11eb-9003-9f68f212f1f8.jpg)
)

Referencing https://github.com/adaptlearning/adapt_framework/issues/3125

**Comment by oliverfoster** [comment]
fixed in https://github.com/adaptlearning/adapt_framework/pull/3127

**Comment by tomallpress** [comment]
Tried again after applying fix to the grunt folder, and now getting the following error. I do have the export.json in the de folder it's referring to.
![Untitled](https://user-images.githubusercontent.com/7137955/114720239-c3dd0e00-9d2f-11eb-837d-fea83a236b9d.png)

 Happy to catch up separately
