### ISSUE TITLE
typeerror location replace is not a function

### ISSUE THREAD

**Issue by robertmausser** [cgkineo/rub-cli#40]
After updating to latest rub cli I get 

"typeerror location replace is not a function"

after trying to run "rub zip"

**Comment by oliverfoster** [comment]
please update and try again, apologies
you should probably update node

**Comment by oliverfoster** [comment]
which version of node are you using?

**Comment by oliverfoster** [comment]
it's ok, it was my fault. please update rub again. apologies.
