### ISSUE TITLE
running additional scripts using scriptSafe tag in helper.js

### ISSUE THREAD

**Issue by aniketdharia** [cgkineo/rub-cli#44]
The additional scripts using regular grunt build --prod commands but those scripts are skipped when we use rub build.

**Comment by oliverfoster** [comment]
You'll need to `npm install -g rub-cli` to update rub to version 0.1.12.

And use these instructions:

### framework
`config.json`
```json
{
  "build": {
    "scriptSafe": "adapt-contrib-spoor, adapt-contrib-xapi, adapt-myplugin"
  }
}
```

### adapt-myplugin

`scripts/post-build.js`
```js
module.exports = function(fs, path, log, options, done) {
  // your code here
  done();
};
```

`bower.json`
```json
  "scripts": {
    "adaptpostbuild": "/scripts/post-build.js"
  }
```
