### ISSUE TITLE
tracking:insert/remove/reset not working

### ISSUE THREAD

**Issue by aniketdharia** [cgkineo/rub-cli#46]
Hi @oliverfoster: The tracking ids insert/remove/reset commands have stopped working. They are just deleting the trackingIds from the blocks.json file and not adding them back in or updating the numbers.

**Comment by oliverfoster** [comment]
working as of 0.2.5

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/3465

**Comment by swashbuck** [comment]
Closing this ticket. I just retested tracking reset, insert, and remove, both with and without Spoor enabled. Everything seems fine now.
