### ISSUE TITLE
Add documentation for the pathways from adapt-cli to a builds folder

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/rub-cli#48]
Please add a section to the readme regarding the pathways from adapt-cli to a builds folder (i.e. using rub-cli instead of grunt).  This should cover:

- Manually creating the 'builds' folder.
- After running `grunt build`, moving the new course into the 'builds' folder.
- Deleting the 'course' folder in 'src'.  Otherwise, the 'build' folder will keep being recreated when rub is ran.

Note that this does not apply when using adapt-setup instead of adapt create course.  However, it should still be documented.

Thanks.

**Comment by oliverfoster** [comment]
Could you do it?

**Comment by swashbuck** [comment]
> Could you do it?

Yep, on it.
