### ISSUE TITLE
Fresh install of rub only returns 'Unsupported architecture.'

### ISSUE THREAD

**Issue by matthorton16** [cgkineo/rub-cli#51]
I very recently did a fresh install of the adapt framework. When trying to run any of my previous projects using `rub dev` nothing runs, and the only response/report I get is 'Unsupported architecture.' Not sure where to even begin looking to fix this issue.

**Comment by oliverfoster** [comment]
I'm going to need much more than that. At least a screenshot, the node version number, the operating system you're on.

**Comment by matthorton16** [comment]
![Screen Shot 2022-06-09 at 10 32 25 AM (2)](https://user-images.githubusercontent.com/70723658/172898651-805049e9-63b6-4854-959b-75d3829569c5.png)
I'm on a mac OS Monterey v12.2.1

**Comment by oliverfoster** [comment]
You using docker?

**Comment by matthorton16** [comment]
I am not.

**Comment by oliverfoster** [comment]
Have you compiled adapt in this environment before? And if yes, what have you changed?

**Comment by matthorton16** [comment]
In this environment I have not been able to compile adapt. First time setting this up on this computer.

**Comment by matthorton16** [comment]
Awesome I will give that a go. Thanks!

**Comment by oliverfoster** [comment]
It looks like you've got an arm version of node and that library doesn't have the arm binaries. I'm not sure how/if you can run it in x64 mode on the m1.
