### ISSUE TITLE
AAT Builds are failing

### ISSUE THREAD

**Issue by aniketdharia** [cgkineo/rub-cli#57]
AAT Builds are failing.

-Z command is not giving an authoring tool zip it is giving the full folder from root with builds/module/adaptbuild instead of AAT builds generated earlier.

**Comment by aniketdharia** [comment]
@oliverfoster

**Comment by NayanKhedkar** [comment]
Its seem that if total file count big node-native-zip-compression fails.
show below screenshots
 
![less_fileworked](https://user-images.githubusercontent.com/16237837/206969516-65314ab6-a918-422a-bbf3-f1bba401b96f.png)
Failed when file count big
![authoring tool error](https://user-images.githubusercontent.com/16237837/206969543-93dd41f7-47ce-42f4-909c-8c3049ff4b49.png)

The above issue get resolved by using  https://www.npmjs.com/package/archiver

Please refer to the PR: https://github.com/cgkineo/rub-cli/pull/62
