### ISSUE TITLE
assets folder removed by build tasks

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/rub-cli#64]
If an `assets` folder is used for common files (e.g. shared across languages) it is removed when running a build task. I don't think this used to happen.

**Comment by oliverfoster** [comment]
could I have an example path relative to the root/ folder please?

**Comment by chris-steele** [comment]
Just did a quick test; in this case it was `builds/m05/assets`. I thought I could put arbitrary files in here to share across languages, but on running `rub dev` etc the folder is recreated and populated only with files present in the `assets` folders of various plugins.

**Comment by oliverfoster** [comment]
You can see in normal grunt, `$ grunt clean` deletes everything in the `outputdir` https://github.com/adaptlearning/adapt_framework/blob/d3e967013199bd293767741c0f8b771acedb5406/grunt/config/clean.js#L17
