### ISSUE TITLE
Regional language codes not importable

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/rub-cli#69]
The `translate:import` command doesn't import as intended if you are attempting to import a language code with a regional sub-language. It seems to be the `-` glyph that isn't accepted. You are able to import with a simpler language code and change your folder name post-import. 

For example:
- English (Canada) - en-ca
- Spanish (Mexico) - es-mx
- Chinese (Taiwan) - zh-tw

**Comment by oliverfoster** [comment]
Could you please paste the entire command or give a screenshot of the output?

**Comment by joe-replin** [comment]
The command:
translate:import --targetLang=fr-FR m05

A 'fr-FR' was placed in both course/ and languagefiles/

**Comment by oliverfoster** [comment]
Could be parameter parsing at this line https://github.com/cgkineo/rub-cli/blob/1c8161f29f5ed570fb9ed271b52f01b9242b5010/globals/terminal.js#L27

**Comment by oliverfoster** [comment]
![image](https://github.com/cgkineo/rub-cli/assets/7974663/9d7e8da3-5134-4499-af46-0ab7d283bb4b)

Works fine here in git bash.

Which operating system and terminal are you using?

**Comment by oliverfoster** [comment]
you'd need to put the translation in the folder languagefiles/m05/fr-FR

**Comment by oliverfoster** [comment]
Did you have any luck or time in trying to replicate this? @joe-replin

**Comment by joe-replin** [comment]
I'm closing this due to inaction.

**Comment by oliverfoster** [comment]
Inaction? You haven't responded to any of my messages.

**Comment by joe-replin** [comment]
Yes, it is my inaction. I am thinking your questions pointed to something I was doing wrong. I believe it is working as intended and see no issue. Feel free to keep this open just in case this exact configuration appears again with region codes.

**Comment by oliverfoster** [comment]
Cool. As long as you're satisfied. I'll close.
