### ISSUE TITLE
minification

### ISSUE THREAD

**Issue by moloko** [cgkineo/rub-cli#9]
rub -b doesn't minify adapt.min.js

`rub build` doesn't either

thought [this](https://github.com/adaptlearning/adapt_framework/pull/1801/files) might solve it but no such luck

Using framework 2.2.5 and latest rub-cli

templates.js needs looking at also

**Comment by oliverfoster** [comment]
I need to update the grunt patches to incorporate the latest bits from open source.
Does grunt build do it if you take a new clone?

**Comment by oliverfoster** [comment]
rub -M does minification now... i remember i removed it because it was so slow. but you can also now do it optionally

**Comment by moloko** [comment]
OK looks like it may have actually been down to [this issue](https://github.com/adaptlearning/adapt_framework/issues/1966)  - as soon as I remove all instances of `let` and `const` from the project, adapt.min.js gets minified fine. Add just one instance back in and it doesn't.
